### ISSUE TITLE
About training settings

### ISSUE THREAD

**Issue by ppeterpp** [ZSDM-HDR/Zero-Shot-Diffusion-HDR#1]
Thanks for your nice work! As for the lr & batchsize for the second stage finetuning, seems like you keep them identical as the first. But during reproduction we found second stage finetuning way more vram consuming than the first stage, that, bs could only be lowered to 3 on A800, is that expected? (batchsize at 8 during first stage takes around 50G per card, is that also expected?)

**Comment by ZSDM-HDR** [comment]
Thanks for your question. Actually, we also lowered the batchsize during the second stage fine-tuning. Besides, if you don't want to conduct the second stage fine-tuning, you can apply the SRO only to the last step of the reverse sampling, which doesn't require training an auxiliary encoder but can also produce visually pleasing images.

**Comment by ppeterpp** [comment]
Do you mean the first stage trained model + SRO at last step is already enough? Here we prepare the mscn and the luma trainset upon Flickr2K HR according to [https://github.com/ZSDM-HDR/Zero-Shot-Diffusion-HDR/blob/main/test.py#L228](url), and carried out 200-epoch first stage training, and the image_log was like below:
Zero-Shot-Diffusion-HDR/image_log/train/control_gs-030846_e-000199_b-000000.png
![image](https://github.com/user-attachments/assets/02a3640f-cb1b-4b72-b3d2-b8f811b73b08)
Zero-Shot-Diffusion-HDR/image_log/train/control_luma_gs-030846_e-000199_b-000000.png
![image](https://github.com/user-attachments/assets/62e2abf8-edee-4dad-975f-1f20ee9a7e2a)
Zero-Shot-Diffusion-HDR/image_log/train/samples_cfg_scale_9.00_gs-030846_e-000199_b-000000.png
![image](https://github.com/user-attachments/assets/481e8204-0873-49f3-8537-ca20571d4ed3)
Zero-Shot-Diffusion-HDR/image_log/train/reconstruction_gs-030846_e-000199_b-000000.png
![image](https://github.com/user-attachments/assets/b43c6819-150c-4361-95a7-ab5c6ee1ce73)
Seems like the model wasn't able to reconstruct the LDR image properly, could anything go wrong here?

**Comment by zrx2000** [comment]
Seems that it isn't too much of a problem. It's normal to have wrong color in logs. You can recover each color channel following the post-processing step introduced in our paper. (The code has not been uploaded yet.) The minor structural distortion can be compensated to some degree by SRO, even if SRO is only applied to the last step as a post-processing operation. If you want even better results, I think you can try to train the model for more iterations.
