### ISSUE TITLE
Luma map extracted

### ISSUE THREAD

**Issue by Roveer** [ZSDM-HDR/Zero-Shot-Diffusion-HDR#3]
Hello, I am very interested in this job.

But I have a doubt about the extraction of **luma map**. The **luma map extracted from HDR during the inference process** does not seem to be aligned with **the luma map extracted from the real image data set during the training process**. Will this cause problems?

Or do you have plans to open source the code related to data preprocessing?

**Comment by ZSDM-HDR** [comment]
Hi, thanks for your interest. We used the pre-processing technique given by Eq. (4) of our conference paper to prepare the conditional input during inference. This technique is also introduced in reference [33]. You can refer to the script `utils/adaptive_lambda.py` in the codebase https://github.com/yael-vinker/unpaired_hdr_tmo. After this global curve mapping, the image should be Gaussian-blurred. The blurred luma map of HDR images should look like these: 
![1](https://github.com/user-attachments/assets/26691c39-5d7f-4034-8b79-e5de880a65b2)
